class ButtonName:
  BTN_BATTLE_SUCCESS = '/btn/BTN_BATTLE_SUCCESS'
  BTN_BATTLE = '/btn/BTN_BATTLE'
  BTN_NEXT = '/btn/BTN_NEXT'
  BTN_QI_QIU = '/btn/BTN_QI_QIU'
  BTN_SPEED = '/btn/BTN_SPEED'
  BTN_START_BATTLE = '/btn/BTN_START_BATTLE'
  BTN_IN_BATTLE = '/btn/BTN_IN_BATTLE'
  BTN_START_MISSION = '/btn/BTN_START_MISSION'
  BTN_LOGIN = '/btn/BTN_LOGIN'
  BTN_LOOP_CAI_SHU = '/btn/BTN_LOOP_CAI_SHU'
  BTN_ACTIVITY_SHI_ZHI = '/btn/BTN_ACTIVITY_SHI_ZHI'
  